version: 2.1

jobs:
  build:
    docker:  #setup doker environment
      - image: cimg/python:3.11
    steps: # define steps 
      - checkout  #code checkout
      - run: python main.py  
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
                

workflows:
  build_and_test:  #workflow name as per your decision
    jobs:
      - build   
      - test:
          requires:  #first build the code, if build pass then testing done
            - build