version: 2.1

jobs:
  build:
    docker:  #setup doker environment
      - image: cimg/python:3.11
    steps: # define steps 
      - checkout  #code checkout
      - run: python main.py  
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: echo "Deploying to production server"
                 
                

workflows:
  build_test_deploy:  #workflow name as per your decision
    jobs:
      - build   
      - test:
          requires:  #test build khatam hona ka badd suru hoga
            - build

      - deploy:
          requires: #deploy suru hoga test khatam hona ka badd
            - test
          filters:
            branches: #deploy sirf main branch pa hoga
              only: main