version: 2.1

jobs:
  build:
    docker:  #setup doker environment
      - image: cimg/python:3.11
    steps: # define steps 
      - checkout  #code checkout
      - run: python main.py  

workflows:
  build_flow:  #workflow name as per your decision
    jobs:
      - build  