version: 2.1

jobs:
  build:
    docker:       #setup doker environment
      - image: cimg/python:3.11  #image name you want
    steps:        #define steps 
      - checkout  #code checkout
      - run: python main.py  #run container
  test:
    docker:       #setup docker environment
      - image: cimg/python:3.11  #image name you want
    steps:        #define steps
      - checkout  #checkout your code
      - run: python tests.py #run container
  deploy:
    docker:       #setup doker environment
      - image: cimg/python:3.11  #image name you want
    steps:        #define steps
      - checkout  #checkout your code
      - run: echo "Deploying to production server"  #display output 
                 
                

workflows:
  build_test_deploy:  #workflow name as per your decision
    jobs:
      - build   
      - test:
          requires:  #test build khatam hona ka badd suru hoga
            - build

      - deploy:
          requires: #deploy suru hoga test khatam hona ka badd
            - test
          filters:
            branches: #deploy sirf main branch pa hii hoga
              only: main  #name of branch, where you have your code